name: PocketFI

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install user-agents cloudscraper axios colors p-limit https-proxy-agent socks-proxy-agent

    - name: Run Meomundep Script
      run: |
        node meomundep.js || echo "An error occurred during execution."
      continue-on-error: true
